### ISSUE TITLE
Очень узкие отступы

### ISSUE THREAD

**Issue by sashabeep** [64j/templatesedit3#11]
2.0

Отступ от правого края формы без плагина:
<img width="134" alt="Снимок экрана 2019-11-07 в 00 02 35" src="https://user-images.githubusercontent.com/5689796/68337626-f5d95200-00f1-11ea-8029-760fb32949db.png">

С плагином - выходит за пределы таба:
<img width="1166" alt="Снимок экрана 2019-11-06 в 23 54 14" src="https://user-images.githubusercontent.com/5689796/68337663-0ab5e580-00f2-11ea-803e-ddb357b5093e.png">

**Comment by 64j** [comment]
@sashabeep 
Проверь из дев ветки.

**Comment by sashabeep** [comment]
@64j вроде всё правильно стало
