### ISSUE TITLE
Менять курсор в зависимости от действия

### ISSUE THREAD

**Issue by Ruslan-Aleev** [64j/templatesedit3#12]
Т.к. курсор не меняется в зависимости от действия пользователя, то возникают непонятки:
- Не понятна область перетаскивания блоков;
- Не понятно захватился ли элемент или нет;
- Доступно ли меню для редактирования и т.п.

Особенно видно, когда Дмитрий в своих видео в 40-50% промахивается - https://youtu.be/FVX63RRYsU4?t=618

Спасибо за компонент!

**Comment by 64j** [comment]
Не вижу никаких проблем.
https://monosnap.com/direct/jkHJQG5wECDH7lTGwZf0SNMW6stOlS
