### ISSUE TITLE
Export/Import

### ISSUE THREAD

**Issue by risingisland** [64j/templatesedit3#14]
Any progress on the possibility to export and import templates?
Or possibly select an existing template, or set template as default for all?

**Comment by 64j** [comment]
Yes, you can use the default template for everyone.

**Comment by risingisland** [comment]
To all users, yes, but it would be nice to apply it to all templates as there default, then if modified it would save it as new.
I am not sure if I am explaining it properly?

**Comment by 64j** [comment]
@risingisland 
I.e.
When choosing one template by default, is it set by default for all taking into account the roles of managers?

**Comment by risingisland** [comment]
Sorry, yes, I understand you can set it for users/roles.
What I mean, is an easy way to set a custom layout for all templates. 
Update or replace "configs/template_default.php" with ease.

Once I have a new layout in "template__4__1.json" for example, have this be the global default, so there isnt a need to download it, change name, and re-upload it for the next template.

Maybe this explanation is clearer? Not sure :blush:

**Comment by risingisland** [comment]
Or possibly this idea could work...
Add a new button, that when clicked would display the code for the layout being built:
![template-edit](https://user-images.githubusercontent.com/6113504/70044366-23fb6600-15ba-11ea-95dd-d026b2043b34.png)

This code could then be copied and pasted to the next layout:
![template-edit-code](https://user-images.githubusercontent.com/6113504/70044520-6de44c00-15ba-11ea-8046-4bc449db8481.png)
This could possibly save time from having to upload and download files from "configs"
Just an idea.

**Comment by risingisland** [comment]
Separate question: At the beginning of the template, there is "tab1555881533064" or something similar.
What is this number? It doesnt look like there is a problem, if more than one template has this same number.

**Comment by 64j** [comment]
In process.

**Comment by 64j** [comment]
@risingisland 
Please check
![image](https://user-images.githubusercontent.com/4653189/71507366-53d61a80-2895-11ea-8c60-3c0ad5998e50.png)

Also, the default config applies to roles

**Comment by risingisland** [comment]
Nice, will test today and let you know. Thanks!

**Comment by risingisland** [comment]
OK, with first test, Firefox has problems. The two buttons do not work.
Under Chrome, both work fine.
This is looking nice.

**Comment by risingisland** [comment]
Hmm, the buttons seem to be working now.
Will do a bit more testing, but it seems to be fine in FF now. Also tried in incognito mode and all is fine.
Will report back if I notice anything, but all seems to work fine.

**Comment by risingisland** [comment]
Created a clean install of Evo, added TemplatesEdit3, everything works perfect, as far as I can tell, in both Chrome and FF. I have found no problems. Awesome work!!
