### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by projkin** [64j/templatesedit3#16]
![Clip2net_191218145215](https://user-images.githubusercontent.com/54156948/71080402-7f2a7c80-21a6-11ea-8d8b-39667ce802bd.png)

Ставим 1.4.9 с гита с релизов, ставим те3 через экстрас. делаем конфиг для главного шаблона через веб интерфейс. Далее добавляем еще шаблон, пытаемся там сохранить изменения и вот такая ошибка. php v7.0-7.3 разные пробовал. Права на папки 755 Файлы 644

**Comment by projkin** [comment]
3.1.4 релиз заработал без проблем

**Comment by 64j** [comment]
@projkin 
В дев ветке исправлено.
