### ISSUE TITLE
Шаблон по умолчанию

### ISSUE THREAD

**Issue by sashabeep** [64j/templatesedit3#17]
После установки плагина без настройки шаблонов, шаблон страницы сильно отличается от того вида, в котором он был по дефолту. Контент вообще переезжает на вторую вкладку, например.

Может, имеет смысл изначально не изменять вид стандартного шаблона, пока конфиг не задан?

**Comment by sashabeep** [comment]
+ чтобы 2 раза не вставать
Без названий TV иногда очень сложно их вспомнить
![Снимок экрана 2020-02-06 в 16 44 02](https://user-images.githubusercontent.com/5689796/73942390-015e3400-4900-11ea-9e81-c0e1889de9c4.png)
![Снимок экрана 2020-02-06 в 16 44 46](https://user-images.githubusercontent.com/5689796/73942392-028f6100-4900-11ea-953c-006b2c594d89.png)

**Comment by 64j** [comment]
Чтобы вспомнить ключ поля, можно по его названию кликнуть мышью с зажатым Ctrl.
Ключ с тегами эво -  сохранится в буфере, вида ```[*pagetitle*]```

**Comment by sashabeep** [comment]
@64j не учитывается CMD, хоть и копирует, но на маке ctrl+клик=правый клик

**Comment by 64j** [comment]
Если использовать вид по умолчанию как в эво, то не всегда понятно установлен ли плагин или нет, не ясно для чего же он тогда нужен.
Не заметив разницы, пользователь скажет, а зачем он, всё тоже самое.
А вот сделать привычный вид, дело одного клика и трёх перетаскиваний и сохранение шаблона  как "по умолчанию".

**Comment by 64j** [comment]
@sashabeep 
Добавил в конфигурацию плагина
![image](https://user-images.githubusercontent.com/4653189/90182892-4f765780-ddbb-11ea-81ed-35fe62d981f7.png)

https://github.com/64j/templatesedit3/commit/233c50016fc0c164f703c24007638250100a1fec
