### ISSUE TITLE
После удаления таба TV пропадают из конца вкладки

### ISSUE THREAD

**Issue by sashabeep** [64j/templatesedit3#19]
Нерасставленные TV по умолчанию добавляются внизу формы. Но если отредактировать конфиг и стереть любую вкладку - TV пропадают из формы и их приходится перетаскивать вручную

**Comment by 64j** [comment]
@sashabeep 

Поля добавляются на вкладку по умолчанию (зелёная галочка)
![image](https://user-images.githubusercontent.com/4653189/90185116-ded13a00-ddbe-11ea-9573-378ee7976315.png)

**Comment by 64j** [comment]
Полагаю, проблема решена.
