### ISSUE TITLE
Font-awesome not loaded

### ISSUE THREAD

**Issue by fourroses666** [64j/templatesedit3#20]
I think the font-awesome styles needs to be loaded. Its missing:

```@import "../../common/font-awesome/css/font-awesome.min.css?v=5.10.2";```

<img width="429" alt="arrows" src="https://user-images.githubusercontent.com/523389/78019862-a9b4d580-7350-11ea-86ad-f1c530f0191e.png">

**Comment by fourroses666** [comment]
This seems to work: in file **/tpl/document.tpl.php**
```@import "/manager/media/style/common/font-awesome/css/font-awesome.min.css?v=5.10.2";```

**Comment by 64j** [comment]
Update from Extras templatesEdit3 - develop

**Comment by fourroses666** [comment]
That seems to work indeed :) Didn't know it was in Extras. 
The "menuindex" boxes look better now (no double border).

Only issue I have is font-sizes are not correct but that is because I have a custom theme.
