### ISSUE TITLE
Load source styles as a file

### ISSUE THREAD

**Issue by fourroses666** [64j/templatesedit3#21]
The source has loaded styles in it. Maybe you can do it better like this;

```<link rel="stylesheet" type="text/css" href="/assets/plugins/templatesedit/css/style.css" />```

<img width="452" alt="source" src="https://user-images.githubusercontent.com/523389/78020269-7161c700-7351-11ea-931f-79c924fb7be0.png">

**Comment by fourroses666** [comment]
For correct right margin add;
`.form-row.row{margin-right:-5px;}`

**Comment by 64j** [comment]
@fourroses666 
Has the problem been resolved?

**Comment by fourroses666** [comment]
What problem do you mean? I don't see any changes in the "development" branche here on Github.
Is there an other version as 3.1.x branche?

**Comment by 64j** [comment]
@fourroses666 
![image](https://user-images.githubusercontent.com/4653189/90245451-6066ad80-de3b-11ea-8813-baef1ce4d744.png)
This creates too much distance to the edge of the page.

**Comment by fourroses666** [comment]
Does it? If it does then keep it as is. 

I lost track of this a little bit. I should install a new demo of EVO and TE3 and need to have a look again.
