### ISSUE TITLE
EVO 2.0.3 and templateEdit3 3.1.4 and eFilter 0.1 - не прячет TV

### ISSUE THREAD

**Issue by zatomant** [64j/templatesedit3#22]
Устанавливаем eFilter и templateEdit3 из Extract.
Настраиваем компоненты по докам.
При активном плагине templateEdit заходим в "товар" и видим лишние TV которые должны были спрятаться согласно настройкам в родительском документе (и работе eFiltre). 
![ef2](https://user-images.githubusercontent.com/25015123/95023021-4a2ede00-0683-11eb-92c6-3f17c931242e.jpg)

Если отключить плагин templateEdit3 - eFilter отрабатывает корректно.
![ef1](https://user-images.githubusercontent.com/25015123/95023018-4438fd00-0683-11eb-9ce6-07b6db04b851.jpg)

Баг в templateEdit3 или в eFilter?

**Comment by 64j** [comment]
@zatomant 
Я не смог настроить eFilter, чтобы воспроизвести проблему. 
Вы можете зайти в чат телеграм https://t.me/evolutioncms, найти в нём меня и скинуть доступы личным сообщением.

**Comment by zatomant** [comment]
Доступ дать не могу,  понимаю что с этим было бы быстрее решить вопрос но такие ограничения.
Судя по всему не срабатывает в плагине eFilterHelper вот это:
 
```
//фикс templatesEdit3
$output .= 'jQuery(".sectionBody").find("#tv' . $k . '").closest(".row.form-row").hide();';
```

**Заменил на вот такое и стало работать:**
```
//фикс templatesEdit3
$output .= 'jQuery(".sectionBody").find("input[name=\'tv' . $k . '\']").closest(".row.form-row").hide();';
```

Опять же, я хз, почему для templatesEdit3 был фикс строкой поиска по ИДешнику find("#tv' . $k . '"), а не по Имени.

**Comment by 64j** [comment]
Данный фикс исправил проблему?
Закрываю ишу?

**Comment by zatomant** [comment]
да. для evo 2.0.3 + eFilter 0.1 и templateEdit3 3.1.4 работает
