### ISSUE TITLE
Duplicate Template settings and Responsive CSS

### ISSUE THREAD

**Issue by fourroses666** [64j/templatesedit3#27]
Hi, nice work on TE3 :)

When you duplicate a Template, maybe its better to keep the same settings as the Template which is duplicated?

----
I noticed on smaller screens the input fields can be improved by making the title full width 

```
.form-row .col-title {
    width: 100%;
}
```

![stack1](https://user-images.githubusercontent.com/523389/104815048-8214f800-5812-11eb-8548-e024ca30aa7e.jpg)
![stack2](https://user-images.githubusercontent.com/523389/104815050-83462500-5812-11eb-8b48-1e89a87ef7d3.jpg)

**Comment by 64j** [comment]
fix https://github.com/64j/templatesedit3/commit/1bb72e5a3f5dd2a71200858102b7bc63c7a2b5d1


Try to install from extras develop version.

When duplicating a template, we do not have an event on which the plugin can fire.

**Comment by fourroses666** [comment]
There is still some issue when having 2 columns and date fields. (EVO2).
We can decrease the width of the title field (when reach 1290px). 
I have added a pull request if you agree on it.

<img width="789" alt="title" src="https://user-images.githubusercontent.com/523389/105005997-55d9c100-5a36-11eb-9ec6-d811cba25c3f.png">

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/105132883-c1866180-5afc-11eb-9f1a-f36f02a9921b.png)

From Extras develop version

**Comment by fourroses666** [comment]
iMac - Firefox - EVO 2.0.4 - Default theme.

Ah, not 1290px, I added the width of the document Tree.

946px and above is okee, smaller as 946px is the problem. 767px is okee.
So maybe we can reduce the with of the Title from 946px (or make it 1 column instead of 2.)

```
@media (max-width: 946px) {
  .form-row .col-title {
      width: 9.5em;
  }
}
```

<img width="941" alt="945px" src="https://user-images.githubusercontent.com/523389/105162248-a58dba80-5b12-11eb-8c1b-fe47bde7af98.png">

**Comment by 64j** [comment]
Update from extras, develop branch.
Date fields are not separated

![image](https://user-images.githubusercontent.com/4653189/105164537-4c2f8680-5b26-11eb-865b-3667e36c15ff.png)

**Comment by fourroses666** [comment]
Seems to be a Firefox issue!
Safari and Chrome where oke.

```
@-moz-document url-prefix() {
    -- firefox only --
}
```

**Comment by 64j** [comment]
So this is a problem in firefox for bootstrap 4

**Comment by fourroses666** [comment]
Oke, will close this issue. Good improvement to show 100% width on the title fields for mobile 👍
