### ISSUE TITLE
How to setup blank template

### ISSUE THREAD

**Issue by fourroses666** [64j/templatesedit3#29]
Hi Serg, is there an easy way to "setup" template blank?

**Comment by 64j** [comment]
Create the desired view in the constructor and export to the **assets/plugins/templatesedit/configs** folder with the name **template__0__1.json**

![image](https://user-images.githubusercontent.com/4653189/110838912-113f0900-82b4-11eb-88d2-ef1b0268e5d7.png)

**Comment by fourroses666** [comment]
Ah so blank always takes the configuration of `template__0__1.json`.

Thanks, will look into that.

(Will close issue when checked)

**Comment by fourroses666** [comment]
Thanks!
