### ISSUE TITLE
Hide a TV on x

### ISSUE THREAD

**Issue by fourroses666** [64j/templatesedit3#30]
Wonder if you know a way to hide / show a TV on certain pages / ID(s).
Sometimes you need to add a complete new Template because it has 1 or 2 new TVs.

With the old mm_rules it was possible to hide TVs on IDs.
Would be very welcome to have such functionality.
No idea how that would look like though..

**Comment by 64j** [comment]
This can be done if the config files are created manually in php.

**Comment by fourroses666** [comment]
Ah, so you have to do it before json is parsed probably?

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/111667340-a8144400-8825-11eb-9935-5bebfdfde502.png)

**Comment by fourroses666** [comment]
Hmm, oke. Possible but a bit much work. Or can you choose to have a template saved in JSON or PHP?

Also wonder what this means in the plugin configuration: excludeTvCategory

**Comment by 64j** [comment]
excludeTvCategory - exclude TV from categories with id ... 1, 2, 3
