### ISSUE TITLE
Duplicating templates

### ISSUE THREAD

**Issue by 64j** [64j/templatesedit3#32]
@fourroses666

There is little opportunity to copy templates.

1. Upgrade from Extras develop branch
2. Copy the file **manager/processors/duplicate_template.processor.php** and save in a new path **manager/media/style/default/processors/duplicate_template.processor.php**
3. Add changes to the new file on the very last line (added parameter **&d=$id**)
```php
$header="Location: index.php?r=2&a=16&id=$newid&d=$id";
header($header);

**Comment by fourroses666** [comment]
Nice its possible but I guess its easier to use an export.
