### ISSUE TITLE
Can't install on PHP 8

### ISSUE THREAD

**Issue by fourroses666** [64j/templatesedit3#36]
Tested on PHP 7.4 and that did work. 

```
« Evolution CMS Parse Error »
Error : Undefined array key 2

Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | /home/.../domains/....nl/public_html/assets/modules/store/installer/instprocessor-fast.php
Line | 545
Source | $property[$key['0']]['0']['value'] = trim($arr['2']);


```

**Comment by fourroses666** [comment]
After Installing on PHP 7.4 and setting back to PHP 8 I get this error on the Resource page:

```
« Evolution CMS Parse Error »
Error : Undefined array key "id"

Error information |  
-- | --
ErrorType[num] | WARNING[2]
File | /home/.../domains/....nl/public_html/assets/plugins/templatesedit/tpl/input.tpl.php
Line | 1
Source | <input type="<?= $data['type'] ?>" id="<?= $data['id']  ?>" class="<?= $data['class'] ?>" name="<?= $data['name']  ?>" maxlength="<?= $data['maxlength'] ?>" value="<?=  $data['value'] ?>" onchange="<?= $data['onchange'] ?>" <?=  $data['attr'] ?> />

```

**Comment by fourroses666** [comment]
Somehow it now does work on my testsite with PHP 8.0.12..

**Comment by cimt** [comment]
PHP 8.0.16
Clean EVO 3.1.9 install

Error : Undefined array key 2

Error information 	
ErrorType[num] 	WARNING[2]
File 	D:\laragon\www\evolution319\assets\modules\store\installer\instprocessor-fast.php
Line 	545
Source 	$property[$key['0']]['0']['value'] = trim($arr['2']);

**Comment by 64j** [comment]
@fourroses666 , @cimt 
Can't check because Extras is blocked in RF. But judging by the error, this is a problem in the Store (Extras) module.

**Comment by 64j** [comment]
@fourroses666 
Update from develop branch

**Comment by fourroses666** [comment]
Don't know why but I had no issues last time I checked it.
> Somehow it now does work on my testsite with PHP 8.0.12..

Will test when I have some spare time if the commit has any (new) issues.
Thanks for fix. TE3 really is a nice plugin.

**Comment by cimt** [comment]
@64j 
Thanks for fix... but
unfortunately I have **exactly** the same error!

**Comment by 64j** [comment]
> @64j Thanks for fix... but unfortunately I have **exactly** the same error!

That's right.
So far, I see an error only from the side of the Extras module

**Comment by risingisland** [comment]
@64j Sorry if this is a dumb question, but this update should be fine for those of us who are still using v1.4.x?

**Comment by 64j** [comment]
@risingisland 
I only use 1.4.
I was not going to switch to version 3.x.
But TemplatesEdit3 should work on both versions.

**Comment by 64j** [comment]
> PHP 8.0.16 Clean EVO 3.1.9 install
> 
> Error : Undefined array key 2
> 
> Error information ErrorType[num] WARNING[2] File D:\laragon\www\evolution319\assets\modules\store\installer\instprocessor-fast.php Line 545 Source $property[$key['0']]['0']['value'] = trim($arr['2']);

Fixed https://github.com/64j/templatesedit3/commit/18391c8c5ef936915c76f6887b30e7c737f1f9ef#diff-7139868bba9fc14b838030616752a96722d57b50688551dfc561afa9363bb73aR10

**Comment by cimt** [comment]
Super, thank you! Runs without errors.
@64j One question please:
 what do you use afterwards, if 1.4 is not further developed???
I would much rather stick with 1.4 too!,,, I thought 1.4 would end with PHP8!?

**Comment by 64j** [comment]
> Super, thank you! Runs without errors. @64j One question please: what do you use afterwards, if 1.4 is not further developed??? I would much rather stick with 1.4 too!,,, I thought 1.4 would end with PHP8!?

Evo 1.4 I think will not stop for a long time. Adaptation for php 8, we will correct as errors become available.

**Comment by cimt** [comment]
@64j 
Thank you... that sounds good!
and thanks to everyone who works on it!

**Comment by user83743** [comment]
hi 64j Serg. i hope you're well. do you have evo1.4.17 running without error on php8 or php8.1?  i have a test evo1.4.17 and it runs 100% on php7.4 and when i switch to php8 on cpanel i get a dead white page --- https://forum.evo.im/d/216-evo1417-and-php8-php81/2 . do you recognise that error message by any chance?

**Comment by user83743** [comment]
i got a evo3.1.6 and upgraded it to 3.1.10 on php7.4 and it works fine. i switch over to php8 in cpanel and again - nothing displays. the /error_log file is attached. does anyone recognise anything in that that might indicate why php 8 is not working on evo3.1.10 either? some advanced developers may have a hack to get it working but i don't . i should be able to get a evo install to 3.1.10 and expect that it would run in php8, correct?

[http://ams2services.com/evo3.1.10--error_log.txt]

**Comment by fourroses666** [comment]
I'm not an expert on this issue. Could also be an issue with collation of database tables or something like openbasedir.

**Comment by user83743** [comment]
thanks for the feedback @fourroses666 .   would that affect a perfectly working evo1.4.17 or evo3.1.10 website? all i did was change the php version in both cases from 7.4 to 8 - so the mysql/database connections were working. i am amazed that neither can connect with days of debug. are you using maria db 10.2? here is my settings page - anything different to your working evo3.1.10 installation?



Evolution CMS version	 	3.1.10
Release date	 	Mar 01, 2022
PHP Version	 	[7.4.28](javascript:;)
Access permissions	 	Enabled
Server Time	 	08:24:49
Local Time	 	09:24:49
Server offset	 	1 h
Database name	 	amsservi_dummyevo3customelectronics
Database server	 	localhost
Database Version	 	10.2.43-MariaDB
Database Charset	 	latin1
Database Collation Charset	 	latin1_swedish_ci
Table prefix	 	modx_
MODX_BASE_PATH	 	/home/amsservi/public_html/xxxx.ie/
MODX_BASE_URL	 	/xxxx.ie/
MODX_MANAGER_URL	 	https://ams2services.com/xxxx.ie/manager/
MODX_MANAGER_PATH	 	/home/amsservi/public_html/xxxx.ie/manager/
MODX_SITE_URL	 	https://ams2services.com/xxxx.ie/

**Comment by fourroses666** [comment]
Afaik you need to change database collation for EVO 3
'charset' => env('DB_CHARSET', 'utf8mb4'), // $database_connection_charset
'collation' => env('DB_COLLATION', 'utf8mb4_general_ci'), //$database_collation

Don't know if it will solve your issue. Before switching PHP version you can also "disable" all plugins and see if that works.

**Comment by user83743** [comment]
thanks @fourroses666 - i tried those 2 settings in /public_html/domain.com/core/config/database/connections/default.php and the same dead white screen appears when i go to php8.

i disabled all plugins and it's the same on php8.

but i switched to php8.1 as a guess, and the /manager loads fine with no apparent errors, but the site won't load but it's a php language error only (below). maybe i can put in a fix/hack and get that to load?


################

strlen(): Passing null to parameter #1 ($string) of type string is deprecated
« Evolution CMS Parse Error »
Error : The magic method Helpers\FS::__wakeup() must have public visibility
Error information	
ErrorType[num]	WARNING[2]
File	/home/amsservi/public_html/xxxx.ie/assets/lib/Helpers/FS.php
Line	55
Source	private function __wakeup()

Basic info	
REQUEST_URI	http://ams2services.com:443/xxxx.ie/
Resource	[1] [Custom Electronics](https://ams2services.com/xxxx.ie/)
Referer	https://ams2services.com/xxxx.ie/manager/
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
IP	80.111.51.74
Current time	2022-03-14 09:49:07

Benchmarks	
MySQL	0.0000 s (0 Requests)
PHP	0.1314 s
Total	0.1314 s
Memory	19.594146728516 mb

Backtrace
EvolutionCMS\Core->processRoutes()
index.php on line 137
Illuminate\Routing\Router->dispatch(Illuminate\Http\Request $var1)
core/src/Core.php on line 2701
Illuminate\Routing\Router->dispatchToRoute(Illuminate\Http\Request $var1)
core/vendor/illuminate/routing/Router.php on line 651
Illuminate\Routing\Router->runRoute(Illuminate\Http\Request $var1, Illuminate\Routing\Route $var2)
core/vendor/illuminate/routing/Router.php on line 662
Illuminate\Routing\Router->runRouteWithinStack(Illuminate\Routing\Route $var1, Illuminate\Http\Request $var2)
core/vendor/illuminate/routing/Router.php on line 698
Illuminate\Pipeline\Pipeline->then(Closure $var1)
core/vendor/illuminate/routing/Router.php on line 723
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Illuminate\Http\Request $var1)
core/vendor/illuminate/pipeline/Pipeline.php on line 103
Illuminate\Routing\Router->Illuminate\Routing\{closure}(Illuminate\Http\Request $var1)
core/vendor/illuminate/pipeline/Pipeline.php on line 128
Illuminate\Routing\Route->run()
core/vendor/illuminate/routing/Router.php on line 721
Illuminate\Routing\Route->runCallable()
core/vendor/illuminate/routing/Route.php on line 208
EvolutionCMS\Extensions\Router->EvolutionCMS\Extensions\{closure}()
core/vendor/illuminate/routing/Route.php on line 238
EvolutionCMS\Core->executeParser()
core/src/Extensions/Router.php on line 25
EvolutionCMS\Core->prepareResponse()
core/src/Core.php on line 2763
EvolutionCMS\Core->outputContent()
core/src/Core.php on line 2979
EvolutionCMS\Core->parseDocumentSource(string $var1)
core/src/Core.php on line 784
EvolutionCMS\Core->evalSnippets(string $var1)
core/src/Core.php on line 2650
EvolutionCMS\Core->_get_snip_result(string $var1)
core/src/Core.php on line 1993
EvolutionCMS\Core->evalSnippet(string $var1, array $var2)
core/src/Core.php on line 2082
eval()
core/src/Core.php on line 1918
require(string $var1)
core/src/Core.php(1918) : eval()'d code on line 1
EvolutionCMS\Core->runSnippet('DocLister', array $var2)
assets/snippets/DocLister/snippet.DLMenu.php on line 19
EvolutionCMS\Core->evalSnippet(string $var1, array $var2)
core/src/Core.php on line 4417
eval()
core/src/Core.php on line 1918
require(string $var1)
core/src/Core.php(1918) : eval()'d code on line 1
require_once(string $var1)
assets/snippets/DocLister/snippet.DocLister.php on line 15
include_once(string $var1)
assets/snippets/DocLister/core/DocLister.abstract.php on line 9

**Comment by fourroses666** [comment]
Maybe DocLister needs an update. I also see: Error : The magic method Helpers\FS::__wakeup() must have public visibility.
Maybe FTP CHMOD isn't correct. I really don't know. Sometimes an EVO re-update fixes issues.
https://github.com/evolution-cms/installer

**Comment by user83743** [comment]
thanks . i will check doclister version.  i will try a clean install too
later. does that link https://github.com/evolution-cms/installer install a
brand new install and delete all current files? and clear database? or it
upgrades all files to latest version?

do you have a php8 server running evo3.1.* ?

**Comment by user83743** [comment]
if i go into that evo1.4.10 on php7.4 and look at the doclister it says
version 2.6.2 . if i go to extras and look for it there it says that the
latest version is 2.5.2 . any ideas what you have working?

**Comment by user83743** [comment]
i have evo1.1.10 working on php8.1 now. don't know why, but it does. it
wasn't working a minute ago and is now.

Evolution CMS version 3.1.10
Release date Mar 01, 2022
PHP Version 8.1.3
Access permissions Enabled
Server Time 09:18:27
Local Time 10:18:27
Server offset 1 h
Database name amsservi_dummyevo3customelectronics
Database server localhost
Database Version 10.2.43-MariaDB
Database Charset latin1
Database Collation Charset latin1_swedish_ci

**Comment by fourroses666** [comment]
> does that link https://github.com/evolution-cms/installer install a brand new install and delete all current files? and clear database? or it upgrades all files to latest version?

Just an update. upload install.php in your root folder and go to here-my-site.com/install.php
It will update EVO not all plugins. Not sure if DocLister is default in EVO.




> do you have a php8 server running evo3.1.* ?

Yes on 8.0.12 with only TemplateEdit3 and MultiTV running on it.

Just take in mind that if you update PHP it could be a plugin needs an update because lately many plugins just got fixed for PHP8.



> if i go into that evo1.4.10 on php7.4 and look at the doclister it says version 2.6.2 . if i go to extras and look for it there it says that the latest version is 2.5.2 . any ideas what you have working?

I don't see DocLister on the Plugins page so I guess its a default plugin in EVO. I have no time to dig into that. I guess when installing DocLister you update the default one. The latest version should be found on Github somewhere, download the latest version and install by unpacking on the Extras.

> wasn't working a minute ago and is now.
Might be some cache issues or the update fixed it?
I had some hickups too at first.

**Comment by fourroses666** [comment]
> i have evo1.1.10 working on php8.1 now. don't know why, but it does. it wasn't working a minute ago and is now.

Could be when you save Configuration the cache gets cleared.

**Comment by user83743** [comment]
true. as always, thanks @fourroses666 . i am delighted that i have a working install. now i will update plugins and use it and see if error messages start appearing

**Comment by fourroses666** [comment]
Always good to point out if there are any issues

**Comment by user83743** [comment]
hi @fourroses666 . that installer https://github.com/evolution-cms/installer  only installs a new codebase. how to you upgrade an existing website from 1.4.17 to 3.1.10 ? is there a simple plugin/addon to do it in the evo1.4.17 cms?

**Comment by fourroses666** [comment]
This question needs to be on the forum.
Its because it can't find the config file. Its on an other location.
If you don't use a front-end user system you are probably good to go.
But its probably not needed to update to v3.

Some more info can be found here:
https://forum.evo.im/d/5-how-to-upgrade-evo-1-to-evo-2
https://forum.evo.im/d/49-how-to-upgrade-evo-2-to-evo-3

You should not update to v2. Pick v3 instead.
After upgrade you need to re-update v3 again. I noticed it fixes some issue.

**Comment by user83743** [comment]
thanks MARC for the update. are you serious that we need to install evo3.1.10 twice? to get all updates?  that sounds crazy :)

your two links are for updating 1.x to 2.x and 2.x to 3.x . is there an install to go straight from 1.x to 3.x? or we have to do those 2 updates , once after another?

**Comment by fourroses666** [comment]
There is video, you can update 1 -> 3 directly after you installed the Extra "Migrate 1.4.12 and 2.0.4 to 3.0"
https://forum.evo.im/d/5-how-to-upgrade-evo-1-to-evo-2/9

It just more save to re-update. I think there was a missing file or something and the error wasn't a big deal.

**Comment by user83743** [comment]
thanks @fourroses666

**Comment by user83743** [comment]
on https://forum.evo.im/d/5-how-to-upgrade-evo-1-to-evo-2 when going from evo1.4.17 to evo3.1.10 , it says to go to /assets/update.php and the file is there, but i can't go to/assets/update.php in my browser. i changed permission of the folder and file and still no access. the error message is  "403
Forbidden
Access to this resource on the server is denied!" . i put the update.php file in the root folder, but it throws an error that it can 't reach the config file. have you come across that ? i am not on a pure root domain in this install  - i am on domain1.com/domain2.com - maybe that is the issue?

**Comment by user83743** [comment]
i removed the .htaccess in /assets folder and now the update.php file appears to be loading and then redirects from https://domain1.com/domain2.com/assets/update.php    to https://domain1.com/assets/update.php?step=2  so it removed the domain2.com so the subdomain could be an issue

**Comment by fourroses666** [comment]
I don't know. I don't use subdomains. Sorry but no time to help you any further. You can place a question on the forum.
