### ISSUE TITLE
Undefined array key "caption"

### ISSUE THREAD

**Issue by cimt** [64j/templatesedit3#44]
Hello,
Undefined array key "caption" ... line 261 in file ".../class/templateseditbuilder.class.php".

After a lot of testing, I commented out the line.
I don't know what this line is used for, but strangely enough it works without errors

Clean installation of Evolution CE 3.1.12
PHP 8.0 and 8.1

**Comment by fourroses666** [comment]
In the forum you commented;

'title' => $v['caption'],     
 
replaced it with this:
'title' => $v['caption'] ?? '',

After testing it seem to work

**Comment by 64j** [comment]
@cimt 
Does it happen under certain conditions?

**Comment by cimt** [comment]
@64j 
certain conditions? I do not know!?
I installed evo and then templatesedit without further settings!

**I'm just not sure if this solution is correct**
'title' => $v['caption'],
replaced it with this:
'title' => $v['caption'] ?? '',

I hope you can tell us that ;-)

**just for your information, i'm not a developer**
