### ISSUE TITLE
PHP Warning:  Undefined array key "type"

### ISSUE THREAD

**Issue by googan** [64j/templatesedit3#52]
Evo 1.4.33 php 8.0
Error.log заполняют такие строки, после редактирования шаблона.
![2024-01-05_21-42-16](https://github.com/64j/templatesedit3/assets/18675033/0ba73f66-ab30-4484-a782-ce7520a68009)

**Comment by helgispbru** [comment]
Такой костыль решает:

было:
`if ($this->evo->getConfig('use_editor') == 1 && ($data['type'] == 'richtext' || $data['type'] == 'htmlarea')) {`

стало:
`if ($this->evo->getConfig('use_editor') == 1 && !empty($data['type']) && ($data['type'] == 'richtext' || $data['type'] == 'htmlarea')) {`
