### ISSUE TITLE
Feature: show only when template ID or page ID = x

### ISSUE THREAD

**Issue by fourroses666** [64j/templatesedit3#54]
Hi, I don't know if its possible but I think it would be nice to show/hide a field based on template ID = x or on page ID = x. 

(Used to be able with "mm_rules".)

**Comment by 64j** [comment]
@fourroses666 
It is possible if you use php configs

#56


Make file assets/plugins/templatesedit/configs/<tpl_id>.php
Default config: assets/plugins/templatesedit/configs/template__default.php

![image](https://github.com/64j/templatesedit3/assets/4653189/0f78921a-6a56-42f5-a7fc-361b9f0bd649)

**Comment by fourroses666** [comment]
Cool, thanks. Always like the easiest way and try to do as less code as possible but I probably this is the easiest way to do it.
