### ISSUE TITLE
Feature: Seperations / <hr/> / Header

### ISSUE THREAD

**Issue by fourroses666** [64j/templatesedit3#55]
Would be nice to be able to add a (blank) <hr /> field with TemplateEdit and/or Header so you can make nice seperations. 

Like this on ClientSettings:
https://github.com/mnoskov/clientsettings/issues/6

**Comment by 64j** [comment]
@fourroses666 
Custom TV

![image](https://github.com/64j/templatesedit3/assets/4653189/906bafd6-5ee4-4daf-9b64-c27700652edf)

**Comment by fourroses666** [comment]
Thats great :) thanks !
