### ISSUE TITLE
Evo 1.4.8?

### ISSUE THREAD

**Issue by risingisland** [64j/templatesedit3#6]
Is this compatible with Evo 1.4.8?
Having trouble getting it to work properly.
I saw the video posted by dmi3yy, but can not seem to get the builder to work as shown.
Initially it did not display in Templates until I added "OnTempFormRender" to plugin System Events.
But even then, it does not allow to make changes. Not sure if I am missing something?

Also, any plans to move text to lang files, so that it can be translated easily?

**Comment by 64j** [comment]
@risingisland 
Installed from extras?

**Comment by risingisland** [comment]
Yes, installed via Extras

**Comment by 64j** [comment]
Try to install develop
https://github.com/64j/templatesedit3/tree/3.1.x

**Comment by risingisland** [comment]
OK, getting closer. Now, with this install I get:

![My Evolution Site   EVO CMS Manager ](https://user-images.githubusercontent.com/6113504/56463202-f2d17b00-63c6-11e9-9a82-9b3be31e412f.png)

**Comment by 64j** [comment]
Clear browser cache

**Comment by risingisland** [comment]
I cleared cache, and also opened in private window.
It still shows the same.

**Comment by 64j** [comment]
Which browser?
Which version?

**Comment by risingisland** [comment]
Tried with Firefox v66.0.3 and Chrome v71.0.3578.98
PHP 7.0 and 7.2
All show the same as screen-capture above.

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/56463304-18b44b00-63da-11e9-8faa-9a52ef2de7bf.png)

**Comment by 64j** [comment]
Take a look.
Perhaps you have several versions of the templatesEdit plugin included

**Comment by risingisland** [comment]
Poop. :sad: 
Any other setting that I was supposed to do after install that I missed?

**Comment by risingisland** [comment]
I dont think so, but going to delete plugin and related folders now, and try one more time...

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/56463339-dccdb580-63da-11e9-9a19-1506ab3546fb.png)

**Comment by risingisland** [comment]
Cleared cache again, deleted folder, installed again. Still no luck. 
Getting late, so maybe try again tomorrow. I dont know whats going on :disappointed: :

**Comment by 64j** [comment]
@risingisland
Send access to the site in slack

**Comment by risingisland** [comment]
Am using on localhost tonight.
Will try on a live site tomorrow and see if I have luck there...
If not, will send you a pm with access.

**Comment by risingisland** [comment]
Slack pm sent...

**Comment by 64j** [comment]
Corrected

**Comment by risingisland** [comment]
Holly crap! 
So what was it?
Was I missing something?

**Comment by risingisland** [comment]
I just added a new tab "Gallery" with a multi-tv, but the Insert buttons do not work?
If I disable TamplateEdit, they are fine.

**Comment by risingisland** [comment]
Possible to hide tab "Access Permissions"?

**Comment by 64j** [comment]
No, this is a technical tab and is shown only to administrators.

**Comment by risingisland** [comment]
OK, Thanks for the info and the absolutely amazing work on this plugin!!

**Comment by risingisland** [comment]
Suggestion: Check mark is green or yellow by default, showing it is active, and grey when not active.

![template3](https://user-images.githubusercontent.com/6113504/56469500-9015c900-6432-11e9-8d3a-1e92e439fae8.png)

**Comment by 64j** [comment]
This indicates which tab will be used by default for untagged TV.

**Comment by 64j** [comment]
@risingisland 
https://youtu.be/WRWa8jR7sbc?t=723
12:03
