### ISSUE TITLE
Show in menu

### ISSUE THREAD

**Issue by risingisland** [64j/templatesedit3#7]
Setting **hidemenu** Default value to 0 does not seem to be working.
Show in menu is still checked by default.

**Comment by 64j** [comment]
Why 0 and not 1?

**Comment by risingisland** [comment]
Because I am an idiot and did not try it first :flushed:

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/56471259-23fa8b80-6459-11e9-8aa6-a593365c822f.png)

**Comment by 64j** [comment]
![image](https://user-images.githubusercontent.com/4653189/56471267-38d71f00-6459-11e9-86a8-becf4e4c1a94.png)

**Comment by 64j** [comment]
Fields donthit and hidemenu used inverse values

**Comment by risingisland** [comment]
Thanks for the info, did not realize it used inverse.
Again, you are doing awesome work.

**Comment by risingisland** [comment]
To re-use a temple on another site, we just copy the .json files?

**Comment by 64j** [comment]
```template__<template ID>__<role ID>.json```


![image](https://user-images.githubusercontent.com/4653189/56471390-9324af80-645a-11e9-8668-98a650e40938.png)

**Comment by 64j** [comment]
in the future we plan to add import / export
