### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by risingisland** [64j/templatesedit3#8]
Here is the Spanish translation to add to the lang folder.

[spanish.zip](https://github.com/64j/templatesedit3/files/3101536/spanish.zip)

**Comment by risingisland** [comment]
https://github.com/64j/templatesedit3/blob/ac94e150485a2a9fc4f1771f29889f4d5d2d8ab4/assets/plugins/templatesedit/lang/english.php#L17

Update to: 
   ` 'confirm.del_default' => 'Attention! \nThis will delete the global template.',`

**Comment by 64j** [comment]
Thank.
Added by
https://github.com/64j/templatesedit3/commit/393fd2dccefb79f8e7ef1a7a6643df9fb681c290
